### ISSUE TITLE
"Open image" text at the main panel of application

### ISSUE THREAD

**Issue by Unsimpable2** [POLSL-SE/whaaale#23]
"Open Image" at the main part of application should be as a button or just text? **If it is placeholder for future button, skip this question.** 
If text, it can lead to user misinformation because it is not designed to open any image.
Perhaps changing to "To open file, select 'Open' from 'File' tab at the top left corner or press CTRL + O" would be better.
![image](https://user-images.githubusercontent.com/72402966/208610090-9cec27e4-3b38-4c21-9216-cfe3753b2c3d.png)

**Comment by krzysdz** [comment]
It was meant to be a simple text instructing the user to open a file in order to display something, but since I was writing it very late at night, the sentence was never completed. Yes, it may mislead users into clicking the label instead of using the menu or `Ctrl+o` and I may change it to a more user-friendly message.
